pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'develop',
                    url: 'https://github.com/9739349711/aws-devops-realworld-project.git'
            }
        }

        stage('Build') {
            steps {
                sh '''
                  cd app
                  npm install
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                  cd app
                  npm test
                '''
            }
        }
    }

    post {
        success {
            echo 'CI Pipeline Successful ✅'
        }
        failure {
            echo 'CI Pipeline Failed ❌'
        }
    }
}

